apiVersion: v1
kind: PersistentVolume
metadata:
  name: sparta-db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: standard
  hostPath:
    path: '/mnt/data'
